#!/usr/bin/env python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from __future__ import print_function

import argparse
import os
import shutil
import sys

def main():
     parser = argparse.ArgumentParser()

     parser.add_argument("input_files", metavar="INPUT-FILE", nargs="+")
     parser.add_argument("output_dir", metavar="OUTPUT-DIR")
     parser.add_argument("-a", "--attribute", metavar="NAME=VALUE")
     # XXX Multiple attributes

     args = parser.parse_args()

     if not os.path.exists(args.output_dir):
          os.makedirs(args.output_dir)
     
     for input_file in args.input_files:
          with open(input_file, "r") as f:
               content = f.read()

          name, value = args.attribute.split("=", 1)
          content = content.replace("@{}@".format(name), value)

          input_file_name = os.path.split(input_file)[1]
          output_file = os.path.join(args.output_dir, input_file_name)

          if output_file.endswith(".in"):
               output_file = output_file[:-3]
          
          with open(output_file, "w") as f:
               f.write(content)

          shutil.copymode(input_file, output_file)
     
if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
