FROM centos
MAINTAINER Justin Ross <jross@apache.org>

RUN yum -y update && yum clean all

RUN yum -y install make python-qpid-proton && yum clean all

ADD . /root/qtools
WORKDIR /root/qtools

CMD ["/bin/bash", "-c", "make install PREFIX=/usr && qtools-test"]
