FROM fedora
MAINTAINER Justin Ross <jross@apache.org>

RUN dnf -y update && dnf clean all

RUN dnf -y install make python-qpid-proton && dnf clean all

ADD . /root/qtools
WORKDIR /root/qtools

CMD ["/bin/bash", "-c", "make install PREFIX=/usr && qtools-test"]
