FROM ubuntu
MAINTAINER Justin Ross <jross@apache.org>

RUN apt-get update \
    && apt-get -y install software-properties-common \
    && add-apt-repository ppa:qpid/released

RUN apt-get update \
    && apt-get -y install make python-qpid-proton

ADD . /root/qtools
WORKDIR /root/qtools

CMD ["/bin/bash", "-c", "make install PREFIX=/usr && qtools-test"]
